export interface BijoyKeyItem {
  char: string;
  name?: string;
  keys: string;
  example?: string;
}

export const BIJOY_VOWELS: BijoyKeyItem[] = [
  { char: 'অ', name: 'স্বর অ', keys: 'Shift+F' },
  { char: 'আ', name: 'স্বর আ', keys: 'G + F' },
  { char: 'ই', name: 'হ্রস্ব ই', keys: 'G + D' },
  { char: 'ঈ', name: 'দীর্ঘ ঈ', keys: 'G + Shift+D' },
  { char: 'উ', name: 'হ্রস্ব উ', keys: 'G + S' },
  { char: 'ঊ', name: 'দীর্ঘ ঊ', keys: 'G + Shift+S' },
  { char: 'ঋ', name: 'ঋ', keys: 'G + A' },
  { char: 'এ', name: 'এ', keys: 'G + C' },
  { char: 'ঐ', name: 'ঐ', keys: 'G + Shift+C' },
  { char: 'ও', name: 'ও', keys: 'X' },
  { char: 'ঔ', name: 'ঔ', keys: 'G + Shift+X' },
];

export const BIJOY_CONSONANTS: BijoyKeyItem[] = [
  { char: 'ক', keys: 'J' },
  { char: 'খ', keys: 'Shift+J' },
  { char: 'গ', keys: 'O' },
  { char: 'ঘ', keys: 'Shift+O' },
  { char: 'ঙ', keys: 'Q' },
  { char: 'চ', keys: 'Y' },
  { char: 'ছ', keys: 'Shift+Y' },
  { char: 'জ', keys: 'U' },
  { char: 'ঝ', keys: 'Shift+U' },
  { char: 'ঞ', keys: 'Shift+I' },
  { char: 'ট', keys: 'T' },
  { char: 'ঠ', keys: 'Shift+T' },
  { char: 'ড', keys: 'E' },
  { char: 'ঢ', keys: 'Shift+E' },
  { char: 'ণ', keys: 'Shift+B' },
  { char: 'ত', keys: 'K' },
  { char: 'থ', keys: 'Shift+K' },
  { char: 'দ', keys: 'L' },
  { char: 'ধ', keys: 'Shift+L' },
  { char: 'ন', keys: 'B' },
  { char: 'প', keys: 'R' },
  { char: 'ফ', keys: 'Shift+R' },
  { char: 'ব', keys: 'H' },
  { char: 'ভ', keys: 'Shift+H' },
  { char: 'ম', keys: 'M' },
  { char: 'য', keys: 'W' },
  { char: 'র', keys: 'V' },
  { char: 'ল', keys: 'Shift+V' },
  { char: 'শ', keys: 'Shift+M' },
  { char: 'ষ', keys: 'Shift+N' },
  { char: 'স', keys: 'N' },
  { char: 'হ', keys: 'I' },
  { char: 'ড়', keys: 'P' },
  { char: 'ঢ়', keys: 'Shift+P' },
  { char: 'য়', keys: 'Shift+W' },
  { char: 'ৎ', keys: '\\ (মোবাইলে ? বা Shift+/)' },
  { char: 'ং', keys: 'Shift+Q' },
  { char: 'ঃ', keys: 'Shift+\\ (মোবাইলে / বা |)' },
  { char: 'ঁ', keys: 'Shift+7 (বা ~)' },
];

export const BIJOY_KARS: BijoyKeyItem[] = [
  { char: 'া', name: 'আ-কার', keys: 'F' },
  { char: 'ি', name: 'ই-কার', keys: 'D' },
  { char: 'ী', name: 'ঈ-কার', keys: 'Shift+D' },
  { char: 'ু', name: 'উ-কার', keys: 'S' },
  { char: 'ূ', name: 'ঊ-কার', keys: 'Shift+S' },
  { char: 'ৃ', name: 'ঋ-কার', keys: 'A' },
  { char: 'ে', name: 'এ-কার', keys: 'C' },
  { char: 'ৈ', name: 'ঐ-কার', keys: 'Shift+C' },
  { char: 'ো', name: 'ও-কার', keys: 'X (বা C+F)' },
  { char: 'ৌ', name: 'ঔ-কার', keys: 'Shift+X (বা C+Shift+X)' },
  { char: '্', name: 'হসন্ত (লিঙ্ক)', keys: 'G' },
  { char: '।', name: 'দাঁড়ি', keys: 'Shift+G' },
  { char: '্র', name: 'র-ফলা', keys: 'Z' },
  { char: '্য', name: 'য-ফলা', keys: 'Shift+Z' },
  { char: 'র্', name: 'রেফ', keys: 'Shift+A' },
];

export const BIJOY_CONJUNCTS: BijoyKeyItem[] = [
  { char: 'ক্ত', name: 'ক + ত', keys: 'J + G + K', example: 'ডাক্তার' },
  { char: 'ক্ষ', name: 'ক + ষ', keys: 'J + G + Shift+N', example: 'পরীক্ষা' },
  { char: 'ক্ষ্ণ', name: 'ক + ষ + ণ', keys: 'J + G + Shift+N + G + Shift+B', example: 'তীক্ষ্ণ' },
  { char: 'ক্ষ্ম', name: 'ক + ষ + ম', keys: 'J + G + Shift+N + G + M', example: 'সূক্ষ্ম' },
  { char: 'ক্ষ্ব', name: 'ক + ষ + ব', keys: 'J + G + Shift+N + G + H', example: 'স্বাক্ষর' },
  { char: 'ক্ট', name: 'ক + ট', keys: 'J + G + T', example: 'ডক্টর' },
  { char: 'ক্র', name: 'ক + র', keys: 'J + Z (বা J+G+V)', example: 'চক্র' },
  { char: 'ক্ল', name: 'ক + ল', keys: 'J + G + Shift+V', example: 'ক্লান্ত' },
  { char: 'ক্স', name: 'ক + স', keys: 'J + G + N', example: 'বাক্স' },
  { char: 'খ্য', name: 'খ + য', keys: 'Shift+J + Shift+Z', example: 'খ্যাত' },
  { char: 'খ্র', name: 'খ + র', keys: 'Shift+J + Z', example: 'খ্রিষ্টান' },
  { char: 'গ্র', name: 'গ + র', keys: 'O + Z', example: 'গ্রহণ' },
  { char: 'গ্ধ', name: 'গ + ধ', keys: 'O + G + Shift+L', example: 'মুগ্ধ' },
  { char: 'গ্ন', name: 'গ + ন', keys: 'O + G + B', example: 'মগ্ন' },
  { char: 'গ্ম', name: 'গ + ম', keys: 'O + G + M', example: 'যুগ্ম' },
  { char: 'গ্ল', name: 'গ + ল', keys: 'O + G + Shift+V', example: 'গ্লানি' },
  { char: 'ঘ্ন', name: 'ঘ + ন', keys: 'Shift+O + G + B', example: 'কৃতঘ্ন' },
  { char: 'ঘ্র', name: 'ঘ + র', keys: 'Shift+O + Z', example: 'ঘ্রাণ' },
  { char: 'ঙ্ক', name: 'ঙ + ক', keys: 'Q + G + J', example: 'অঙ্ক' },
  { char: 'ঙ্ক্ষ', name: 'ঙ + ক্ষ', keys: 'Q + G + J + G + Shift+N', example: 'আকাঙ্ক্ষা' },
  { char: 'ঙ্খ', name: 'ঙ + খ', keys: 'Q + G + Shift+J', example: 'শঙ্খ' },
  { char: 'ঙ্গ', name: 'ঙ + গ', keys: 'Q + G + O', example: 'বঙ্গ' },
  { char: 'ঙ্ঘ', name: 'ঙ + ঘ', keys: 'Q + G + Shift+O', example: 'সঙ্ঘ' },
  { char: 'ঙ্ম', name: 'ঙ + ম', keys: 'Q + G + M', example: 'বাঙ্ময়' },
  { char: 'চ্চ', name: 'চ + চ', keys: 'Y + G + Y', example: 'উচ্চ' },
  { char: 'চ্ছ', name: 'চ + ছ', keys: 'Y + G + Shift+Y', example: 'ইচ্ছা' },
  { char: 'চ্ছ্র', name: 'চ + ছ + র', keys: 'Y + G + Shift+Y + Z', example: 'কৃচ্ছ্র' },
  { char: 'চ্ব', name: 'চ + ব', keys: 'Y + G + H', example: 'চত্বর' },
  { char: 'জ্জ', name: 'জ + জ', keys: 'U + G + U', example: 'লজ্জা' },
  { char: 'জ্জ্ব', name: 'জ + জ + ব', keys: 'U + G + U + G + H', example: 'উজ্জ্বল' },
  { char: 'জ্ঞ', name: 'জ + ঞ', keys: 'U + G + Shift+I', example: 'জ্ঞান' },
  { char: 'জ্ঝ', name: 'জ + ঝ', keys: 'U + G + Shift+U', example: 'কুজ্ঝটিকা' },
  { char: 'জ্ব', name: 'জ + ব', keys: 'U + G + H', example: 'জ্বর' },
  { char: 'ঞ্চ', name: 'ঞ + চ', keys: 'Shift+I + G + Y', example: 'কাঞ্চন' },
  { char: 'ঞ্ছ', name: 'ঞ + ছ', keys: 'Shift+I + G + Shift+Y', example: 'বাঞ্ছা' },
  { char: 'ঞ্জ', name: 'ঞ + জ', keys: 'Shift+I + G + U', example: 'ইঞ্জিন' },
  { char: 'ঝ্র', name: 'ঝ + র', keys: 'Shift+U + Z', example: 'ঝর্না' },
  { char: 'ট্ট', name: 'ট + ট', keys: 'T + G + T', example: 'চট্টগ্রাম' },
  { char: 'ট্ম', name: 'ট + ম', keys: 'T + G + M', example: 'কুট্মল' },
  { char: 'ট্ব', name: 'ট + ব', keys: 'T + G + H', example: 'খট্বা' },
  { char: 'ট্র', name: 'ট + র', keys: 'T + Z', example: 'ট্রেন' },
  { char: 'ড্ড', name: 'ড + ড', keys: 'E + G + E', example: 'আড্ডা' },
  { char: 'ড্র', name: 'ড + র', keys: 'E + Z', example: 'ড্রাম' },
  { char: 'ঢ্র', name: 'ঢ + র', keys: 'Shift+E + Z', example: 'মেঢ্র' },
  { char: 'ণ্ট', name: 'ণ + ট', keys: 'Shift+B + G + T', example: 'ঘণ্টা' },
  { char: 'ণ্ঠ', name: 'ণ + ঠ', keys: 'Shift+B + G + Shift+T', example: 'কণ্ঠ' },
  { char: 'ণ্ড', name: 'ণ + ড', keys: 'Shift+B + G + E', example: 'দণ্ড' },
  { char: 'ণ্ঢ', name: 'ণ + ঢ', keys: 'Shift+B + G + Shift+E', example: 'আষাঢ়' },
  { char: 'ণ্ণ', name: 'ণ + ণ', keys: 'Shift+B + G + Shift+B', example: 'বিষণ্ণ' },
  { char: 'ণ্য', name: 'ণ + য', keys: 'Shift+B + Shift+Z', example: 'পুণ্য' },
  { char: 'ত্ত', name: 'ত + ত', keys: 'K + G + K', example: 'উত্তর' },
  { char: 'ত্ত্ব', name: 'ত + ত + ব', keys: 'K + G + K + G + H', example: 'তত্ত্ব' },
  { char: 'ত্থ', name: 'ত + থ', keys: 'K + G + Shift+K', example: 'উত্থান' },
  { char: 'ত্ন', name: 'ত + ন', keys: 'K + G + B', example: 'রত্ন' },
  { char: 'ত্ম', name: 'ত + ম', keys: 'K + G + M', example: 'আত্মা' },
  { char: 'ত্ব', name: 'ত + ব', keys: 'K + G + H', example: 'গুরুত্ব' },
  { char: 'ত্র', name: 'ত + র', keys: 'K + Z', example: 'ছাত্র' },
  { char: 'ত্র্য', name: 'ত + র + য', keys: 'K + Z + Shift+Z', example: 'ত্র্যহস্পর্শ' },
  { char: 'থ্ব', name: 'থ + ব', keys: 'Shift+K + G + H', example: 'পৃথ্বী' },
  { char: 'থ্য', name: 'থ + য', keys: 'Shift+K + Shift+Z', example: 'তথ্য' },
  { char: 'থ্র', name: 'থ + র', keys: 'Shift+K + Z', example: 'নৃথ্র' },
  { char: 'দ্দ', name: 'দ + দ', keys: 'L + G + L', example: 'উদ্দেশ্য' },
  { char: 'দ্ধ', name: 'দ + ধ', keys: 'L + G + Shift+L', example: 'যুদ্ধ' },
  { char: 'দ্ব', name: 'দ + ব', keys: 'L + G + H', example: 'দ্বার' },
  { char: 'দ্ভ', name: 'দ + ভ', keys: 'L + G + Shift+H', example: 'অদ্ভুত' },
  { char: 'দ্ম', name: 'দ + ম', keys: 'L + G + M', example: 'পদ্ম' },
  { char: 'দ্র', name: 'দ + র', keys: 'L + Z', example: 'ভদ্র' },
  { char: 'ধ্ব', name: 'ধ + ব', keys: 'Shift+L + G + H', example: 'ধ্বনি' },
  { char: 'ধ্য', name: 'ধ + য', keys: 'Shift+L + Shift+Z', example: 'ধ্যান' },
  { char: 'ধ্র', name: 'ধ + র', keys: 'Shift+L + Z', example: 'ধ্রুব' },
  { char: 'ধ্ন', name: 'ধ + ন', keys: 'Shift+L + G + B', example: 'কৃতঘ্ন' },
  { char: 'ন্ট', name: 'ন + ট', keys: 'B + G + T', example: 'সেন্টার' },
  { char: 'ন্ঠ', name: 'ন + ঠ', keys: 'B + G + Shift+T', example: 'লন্ঠন' },
  { char: 'ন্ড', name: 'ন + ড', keys: 'B + G + E', example: 'প্যান্ডেল' },
  { char: 'ন্ত', name: 'ন + ত', keys: 'B + G + K', example: 'শান্ত' },
  { char: 'ন্ত্র', name: 'ন + ত + র', keys: 'B + G + K + Z', example: 'যন্ত্র' },
  { char: 'ন্ত্ব', name: 'ন + ত + ব', keys: 'B + G + K + G + H', example: 'সান্ত্বনা' },
  { char: 'ন্থ', name: 'ন + থ', keys: 'B + G + Shift+K', example: 'গ্রন্থ' },
  { char: 'ন্দ', name: 'ন + দ', keys: 'B + G + L', example: 'আনন্দ' },
  { char: 'ন্দ্র', name: 'ন + দ + র', keys: 'B + G + L + Z', example: 'চন্দ্র' },
  { char: 'ন্ধ', name: 'ন + ধ', keys: 'B + G + Shift+L', example: 'অন্ধ' },
  { char: 'ন্ন', name: 'ন + ন', keys: 'B + G + B', example: 'অন্ন' },
  { char: 'ন্ম', name: 'ন + ম', keys: 'B + G + M', example: 'জন্ম' },
  { char: 'ন্ব', name: 'ন + ব', keys: 'B + G + H', example: 'অন্বেষণ' },
  { char: 'প্ট', name: 'প + ট', keys: 'R + G + T', example: 'ক্যাপ্টেন' },
  { char: 'প্ত', name: 'প + ত', keys: 'R + G + K', example: 'সপ্ত' },
  { char: 'প্ন', name: 'প + ন', keys: 'R + G + B', example: 'স্বপ্ন' },
  { char: 'প্প', name: 'প + প', keys: 'R + G + R', example: 'থাপ্পড়' },
  { char: 'প্য', name: 'প + য', keys: 'R + Shift+Z', example: 'প্রাপ্য' },
  { char: 'প্র', name: 'প + র', keys: 'R + Z', example: 'প্রথম' },
  { char: 'প্ল', name: 'প + ল', keys: 'R + G + Shift+V', example: 'প্লাবন' },
  { char: 'প্স', name: 'প + স', keys: 'R + G + N', example: 'লিপ্সা' },
  { char: 'ফ্র', name: 'ফ + র', keys: 'Shift+R + Z', example: 'ফ্রেম' },
  { char: 'ফ্ল', name: 'ফ + ল', keys: 'Shift+R + G + Shift+V', example: 'ফ্ল্যাট' },
  { char: 'ব্জ', name: 'ব + জ', keys: 'H + G + U', example: 'সব্জি' },
  { char: 'ব্দ', name: 'ব + দ', keys: 'H + G + L', example: 'শব্দ' },
  { char: 'ব্ধ', name: 'ব + ধ', keys: 'H + G + Shift+L', example: 'স্তব্ধ' },
  { char: 'ব্ব', name: 'ব + ব', keys: 'H + G + H', example: 'আব্বা' },
  { char: 'ব্ল', name: 'ব + ল', keys: 'H + G + Shift+V', example: 'ব্লক' },
  { char: 'ব্র', name: 'ব + র', keys: 'H + Z', example: 'তীব্র' },
  { char: 'ভ্য', name: 'ভ + য', keys: 'Shift+H + Shift+Z', example: 'সভ্য' },
  { char: 'ভ্র', name: 'ভ + র', keys: 'Shift+H + Z', example: 'ভ্রমণ' },
  { char: 'ম্প', name: 'ম + প', keys: 'M + G + R', example: 'সম্পদ' },
  { char: 'ম্প্র', name: 'ম + প + র', keys: 'M + G + R + Z', example: 'সম্প্রদায়' },
  { char: 'ম্ফ', name: 'ম + ফ', keys: 'M + G + Shift+R', example: 'লম্ফ' },
  { char: 'ম্ব', name: 'ম + ব', keys: 'M + G + H', example: 'অম্বল' },
  { char: 'ম্ভ', name: 'ম + ভ', keys: 'M + G + Shift+H', example: 'সম্ভব' },
  { char: 'ম্ম', name: 'ম + ম', keys: 'M + G + M', example: 'সম্মান' },
  { char: 'ম্ল', name: 'ম + ল', keys: 'M + G + Shift+V', example: 'ম্লান' },
  { char: 'র্ক', name: 'র + ক (রেফ)', keys: 'Shift+A + J', example: 'তর্ক' },
  { char: 'র্গ', name: 'র + গ (রেফ)', keys: 'Shift+A + O', example: 'বর্গ' },
  { char: 'র্ষ', name: 'র + ষ (রেফ)', keys: 'Shift+A + Shift+N', example: 'বর্ষা' },
  { char: 'র্শ', name: 'র + শ (রেফ)', keys: 'Shift+A + Shift+M', example: 'আদর্শ' },
  { char: 'ল্ক', name: 'ল + ক', keys: 'Shift+V + G + J', example: 'বল্কল' },
  { char: 'ল্গ', name: 'ল + গ', keys: 'Shift+V + G + O', example: 'বল্গা' },
  { char: 'ল্ট', name: 'ল + ট', keys: 'Shift+V + G + T', example: 'উল্টো' },
  { char: 'ল্প', name: 'ল + প', keys: 'Shift+V + G + R', example: 'গল্প' },
  { char: 'ল্ল', name: 'ল + ল', keys: 'Shift+V + G + Shift+V', example: 'আল্লাহ' },
  { char: 'শ্চ', name: 'শ + চ', keys: 'Shift+M + G + Y', example: 'নিশ্চয়' },
  { char: 'শ্ন', name: 'শ + ন', keys: 'Shift+M + G + B', example: 'প্রশ্ন' },
  { char: 'শ্ম', name: 'শ + ম', keys: 'Shift+M + G + M', example: 'শ্মশান' },
  { char: 'শ্র', name: 'শ + র', keys: 'Shift+M + Z', example: 'শ্রাবণ' },
  { char: 'শ্ল', name: 'শ + ল', keys: 'Shift+M + G + Shift+V', example: 'শ্লেষ' },
  { char: 'ষ্ট', name: 'ষ + ট', keys: 'Shift+N + G + T', example: 'কষ্ট' },
  { char: 'ষ্ঠ', name: 'ষ + ঠ', keys: 'Shift+N + G + Shift+T', example: 'শ্রেষ্ঠ' },
  { char: 'ষ্ণ', name: 'ষ + ণ', keys: 'Shift+N + G + Shift+B', example: 'কৃষ্ণ' },
  { char: 'ষ্প', name: 'ষ + প', keys: 'Shift+N + G + R', example: 'পুষ্প' },
  { char: 'ষ্ফ', name: 'ষ + ফ', keys: 'Shift+N + G + Shift+R', example: 'নিষ্ফল' },
  { char: 'স্ক', name: 'স + ক', keys: 'N + G + J', example: 'স্কুল' },
  { char: 'স্খ', name: 'স + খ', keys: 'N + G + Shift+J', example: 'স্খলন' },
  { char: 'স্ট', name: 'স + ট', keys: 'N + G + T', example: 'স্টেশন' },
  { char: 'স্ট্র', name: 'স + ট + র', keys: 'N + G + T + Z', example: 'রাষ্ট্র' },
  { char: 'স্ত', name: 'স + ত', keys: 'N + G + K', example: 'ব্যস্ত' },
  { char: 'স্ত্র', name: 'স + ত + র', keys: 'N + G + K + Z', example: 'স্ত্রী' },
  { char: 'স্থ', name: 'স + থ', keys: 'N + G + Shift+K', example: 'স্থান' },
  { char: 'স্ন', name: 'স + ন', keys: 'N + G + B', example: 'স্নান' },
  { char: 'স্প', name: 'স + প', keys: 'N + G + R', example: 'স্পর্শ' },
  { char: 'স্ফ', name: 'স + ফ', keys: 'N + G + Shift+R', example: 'স্ফীত' },
  { char: 'স্ব', name: 'স + ব', keys: 'N + G + H', example: 'স্বাধীন' },
  { char: 'স্ম', name: 'স + ম', keys: 'N + G + M', example: 'স্মরণ' },
  { char: 'স্ল', name: 'স + ল', keys: 'N + G + Shift+V', example: 'স্লোগান' },
  { char: 'হ্ণ', name: 'হ + ণ', keys: 'I + G + Shift+B', example: 'অপরাহ্ণ' },
  { char: 'হ্ন', name: 'হ + ন', keys: 'I + G + B', example: 'চিহ্ন' },
  { char: 'হ্ম', name: 'হ + ম', keys: 'I + G + M', example: 'ব্রাহ্মণ' },
  { char: 'হৃ', name: 'হ + ঋ', keys: 'I + A', example: 'হৃদয়' },
  { char: 'হ্ল', name: 'হ + ল', keys: 'I + G + Shift+V', example: 'আহ্লাদ' },
  { char: 'হ্ব', name: 'হ + ব', keys: 'I + G + H', example: 'আহ্বান' },
  { char: 'হ্র', name: 'হ + র', keys: 'I + Z', example: 'হ্রাস' },
];
