export interface BijoyKeyItem {
  char: string;
  name?: string;
  keys: string;
  example?: string;
}

export const BIJOY_VOWELS: BijoyKeyItem[] = [
  { char: 'অ', name: 'স্বর অ', keys: 'Shift + F', example: 'অনেক, অমর' },
  { char: 'আ', name: 'স্বর আ', keys: 'G + F', example: 'আজ, আকাশ' },
  { char: 'ই', name: 'হ্রস্ব ই', keys: 'G + D', example: 'ইলিশ, ইচ্ছা' },
  { char: 'ঈ', name: 'দীর্ঘ ঈ', keys: 'G + Shift + D', example: 'ঈগল, ঈদ' },
  { char: 'উ', name: 'হ্রস্ব উ', keys: 'G + S', example: 'উট, উৎসব' },
  { char: 'ঊ', name: 'দীর্ঘ ঊ', keys: 'G + Shift + S', example: 'ঊনচল্লিশ, ঊর্মি' },
  { char: 'ঋ', name: 'ঋ', keys: 'G + A', example: 'ঋতু, ঋণ' },
  { char: 'এ', name: 'এ', keys: 'G + C', example: 'এক, এখন' },
  { char: 'ঐ', name: 'ঐ', keys: 'G + Shift + C', example: 'ঐক্য, ঐতিহাসিক' },
  { char: 'ও', name: 'ও', keys: 'X', example: 'ওজন, ওল' },
  { char: 'ঔ', name: 'ঔ', keys: 'G + Shift + X', example: 'ঔষধ, ঔজ্জ্বল্য' },
];

export const BIJOY_CONSONANTS: BijoyKeyItem[] = [
  { char: 'ক', name: 'ক', keys: 'J', example: 'কলম' },
  { char: 'খ', name: 'খ', keys: 'Shift + J', example: 'খবর' },
  { char: 'গ', name: 'গ', keys: 'O', example: 'গল্প' },
  { char: 'ঘ', name: 'ঘ', keys: 'Shift + O', example: 'ঘর' },
  { char: 'ঙ', name: 'ঙ', keys: 'Q', example: 'রঙ' },
  { char: 'চ', name: 'চ', keys: 'Y', example: 'চাঁদ' },
  { char: 'ছ', name: 'ছ', keys: 'Shift + Y', example: 'ছাতা' },
  { char: 'জ', name: 'বর্গীয় জ', keys: 'U', example: 'জল' },
  { char: 'ঝ', name: 'ঝ', keys: 'Shift + U', example: 'ঝড়' },
  { char: 'ঞ', name: 'ঞ', keys: 'Shift + I', example: 'মিঞা' },
  { char: 'ট', name: 'ট', keys: 'T', example: 'টাকা' },
  { char: 'ঠ', name: 'ঠ', keys: 'Shift + T', example: 'ঠিক' },
  { char: 'ড', name: 'ড', keys: 'E', example: 'ডাব' },
  { char: 'ঢ', name: 'ঢ', keys: 'Shift + E', example: 'ঢাক' },
  { char: 'ণ', name: 'মূর্ধন্য ণ', keys: 'Shift + B', example: 'বীণা' },
  { char: 'ত', name: 'ত', keys: 'K', example: 'তারা' },
  { char: 'থ', name: 'থ', keys: 'Shift + K', example: 'থালা' },
  { char: 'দ', name: 'দ', keys: 'L', example: 'দিন' },
  { char: 'ধ', name: 'ধ', keys: 'Shift + L', example: 'ধান' },
  { char: 'ন', name: 'দন্ত্য ন', keys: 'B', example: 'নদী' },
  { char: 'প', name: 'প', keys: 'R', example: 'পাতা' },
  { char: 'ফ', name: 'ফ', keys: 'Shift + R', example: 'ফুল' },
  { char: 'ব', name: 'ব', keys: 'H', example: 'বই' },
  { char: 'ভ', name: 'ভ', keys: 'Shift + H', example: 'ভাত' },
  { char: 'ম', name: 'ম', keys: 'M', example: 'মা' },
  { char: 'য', name: 'অন্তঃস্থ য', keys: 'W', example: 'যাতায়াত' },
  { char: 'র', name: 'ব-শূন্য র', keys: 'V', example: 'রাত' },
  { char: 'ল', name: 'ল', keys: 'Shift + V', example: 'লাল' },
  { char: 'শ', name: 'তালব্য শ', keys: 'Shift + M', example: 'শাপলা' },
  { char: 'ষ', name: 'মূর্ধন্য ষ', keys: 'Shift + N', example: 'ষাঁড়' },
  { char: 'স', name: 'দন্ত্য স', keys: 'N', example: 'সূর্য' },
  { char: 'হ', name: 'হ', keys: 'I', example: 'হাত' },
  { char: 'ড়', name: 'ড-শূন্য ড়', keys: 'P', example: 'বাড়ি' },
  { char: 'ঢ়', name: 'ঢ-শূন্য ঢ়', keys: 'Shift + P', example: 'আষাঢ়' },
  { char: 'য়', name: 'অন্তঃস্থ য়', keys: 'Shift + W', example: 'সময়' },
  { char: 'ৎ', name: 'খণ্ড-ত', keys: '\\ (বা ? / Shift+/)', example: 'উৎসব, চমৎকার' },
  { char: 'ং', name: 'অনুস্বার', keys: 'Shift + Q', example: 'রং, বাংলা' },
  { char: 'ঃ', name: 'বিসর্গ', keys: 'Shift + \\ (বা /)', example: 'দুঃখ, অতঃপর' },
  { char: 'ঁ', name: 'চন্দ্রবিন্দু', keys: 'Shift + 7 (বা ~)', example: 'চাঁদ, হাঁস' },
];

export const BIJOY_KARS: BijoyKeyItem[] = [
  { char: 'া', name: 'আ-কার', keys: 'F', example: 'মা (M+F)' },
  { char: 'ি', name: 'ই-কার (প্রি-কার)', keys: 'D', example: 'কি (D+J)' },
  { char: 'ী', name: 'ঈ-কার', keys: 'Shift + D', example: 'কী (J+Shift+D)' },
  { char: 'ু', name: 'উ-কার', keys: 'S', example: 'তু (K+S)' },
  { char: 'ূ', name: 'ঊ-কার', keys: 'Shift + S', example: 'দূর (L+Shift+S+V)' },
  { char: 'ৃ', name: 'ঋ-কার', keys: 'A', example: 'কৃপা (J+A+R+F)' },
  { char: 'ে', name: 'এ-কার (প্রি-কার)', keys: 'C', example: 'কে (C+J)' },
  { char: 'ৈ', name: 'ঐ-কার (প্রি-কার)', keys: 'Shift + C', example: 'কৈ (Shift+C+J)' },
  { char: 'ো', name: 'ও-কার', keys: 'X (বা C + F)', example: 'কো (C+J+F বা J+X)' },
  { char: 'ৌ', name: 'ঔ-কার', keys: 'Shift + X (বা C+Shift+X)', example: 'কৌ (C+J+Shift+X)' },
  { char: '্', name: 'হসন্ত (যুক্তবর্ণ লিঙ্ক)', keys: 'G', example: 'ক + ্ + ত = ক্ত' },
  { char: '।', name: 'দাঁড়ি (ফুলস্টপ)', keys: 'Shift + G', example: 'আমি বাংলায় গান গাই।' },
  { char: '্র', name: 'র-ফলা', keys: 'Z', example: 'চক্র (Y+J+Z)' },
  { char: '্য', name: 'য-ফলা', keys: 'Shift + Z', example: 'বাক্য (H+F+J+Shift+Z)' },
  { char: 'র্', name: 'রেফ (আগে দিতে হয়)', keys: 'Shift + A', example: 'তর্ক (K+Shift+A+J)' },
];

export const BIJOY_CONJUNCTS: BijoyKeyItem[] = [
  { char: 'ক্ত', name: 'ক + ত', keys: 'J + G + K', example: 'ডাক্তার, রক্ত' },
  { char: 'ক্ষ', name: 'ক + ষ', keys: 'J + G + Shift+N', example: 'পরীক্ষা, ক্ষমা' },
  { char: 'ক্ষ্ণ', name: 'ক + ষ + ণ', keys: 'J + G + Shift+N + G + Shift+B', example: 'তীক্ষ্ণ' },
  { char: 'ক্ষ্ম', name: 'ক + ষ + ম', keys: 'J + G + Shift+N + G + M', example: 'সূক্ষ্ম' },
  { char: 'ক্ষ্ব', name: 'ক + ষ + ব', keys: 'J + G + Shift+N + G + H', example: 'স্বাক্ষর' },
  { char: 'ক্ট', name: 'ক + ট', keys: 'J + G + T', example: 'ডক্টর, অক্টোবর' },
  { char: 'ক্র', name: 'ক + র', keys: 'J + Z (বা J+G+V)', example: 'চক্র, বিক্রম' },
  { char: 'ক্ল', name: 'ক + ল', keys: 'J + G + Shift+V', example: 'ক্লান্ত, ক্লাস' },
  { char: 'ক্স', name: 'ক + স', keys: 'J + G + N', example: 'বাক্স, রিকশা' },
  { char: 'খ্য', name: 'খ + য', keys: 'Shift+J + Shift+Z', example: 'খ্যাত, খ্যাতি' },
  { char: 'খ্র', name: 'খ + র', keys: 'Shift+J + Z', example: 'খ্রিষ্টান' },
  { char: 'গ্র', name: 'গ + র', keys: 'O + Z', example: 'গ্রহণ, গ্রাম' },
  { char: 'গ্ধ', name: 'গ + ধ', keys: 'O + G + Shift+L', example: 'মুগ্ধ, দুগ্ধ' },
  { char: 'গ্ন', name: 'গ + ন', keys: 'O + G + B', example: 'মগ্ন, ভগ্ন' },
  { char: 'গ্ম', name: 'গ + ম', keys: 'O + G + M', example: 'যুগ্ম' },
  { char: 'গ্ল', name: 'গ + ল', keys: 'O + G + Shift+V', example: 'গ্লানি' },
  { char: 'ঘ্ন', name: 'ঘ + ন', keys: 'Shift+O + G + B', example: 'কৃতঘ্ন' },
  { char: 'ঘ্র', name: 'ঘ + র', keys: 'Shift+O + Z', example: 'ঘ্রাণ' },
  { char: 'ঙ্ক', name: 'ঙ + ক', keys: 'Q + G + J', example: 'অঙ্ক, অঙ্কন' },
  { char: 'ঙ্ক্ষ', name: 'ঙ + ক্ষ', keys: 'Q + G + J + G + Shift+N', example: 'আকাঙ্ক্ষা' },
  { char: 'ঙ্খ', name: 'ঙ + খ', keys: 'Q + G + Shift+J', example: 'শঙ্খ' },
  { char: 'ঙ্গ', name: 'ঙ + গ', keys: 'Q + G + O', example: 'বঙ্গ, গঙ্গা' },
  { char: 'ঙ্ঘ', name: 'ঙ + ঘ', keys: 'Q + G + Shift+O', example: 'সঙ্ঘ, লঙ্ঘন' },
  { char: 'ঙ্ম', name: 'ঙ + ম', keys: 'Q + G + M', example: 'বাঙ্ময়' },
  { char: 'চ্চ', name: 'চ + চ', keys: 'Y + G + Y', example: 'উচ্চ, বাচ্চা' },
  { char: 'চ্ছ', name: 'চ + ছ', keys: 'Y + G + Shift+Y', example: 'ইচ্ছা, স্বচ্ছ' },
  { char: 'চ্ছ্র', name: 'চ + ছ + র', keys: 'Y + G + Shift+Y + Z', example: 'কৃচ্ছ্র' },
  { char: 'চ্ব', name: 'চ + ব', keys: 'Y + G + H', example: 'চত্বর' },
  { char: 'জ্জ', name: 'জ + জ', keys: 'U + G + U', example: 'লজ্জা, সজ্জা' },
  { char: 'জ্জ্ব', name: 'জ + জ + ব', keys: 'U + G + U + G + H', example: 'উজ্জ্বল' },
  { char: 'জ্ঞ', name: 'জ + ঞ', keys: 'U + G + Shift+I', example: 'জ্ঞান, অজ্ঞ' },
  { char: 'জ্ঝ', name: 'জ + ঝ', keys: 'U + G + Shift+U', example: 'কুজ্ঝটিকা' },
  { char: 'জ্ব', name: 'জ + ব', keys: 'U + G + H', example: 'জ্বর, জ্বালা' },
  { char: 'ঞ্চ', name: 'ঞ + চ', keys: 'Shift+I + G + Y', example: 'কাঞ্চন, মঞ্চ' },
  { char: 'ঞ্ছ', name: 'ঞ + ছ', keys: 'Shift+I + G + Shift+Y', example: 'বাঞ্ছা' },
  { char: 'ঞ্জ', name: 'ঞ + জ', keys: 'Shift+I + G + U', example: 'ইঞ্জিন, গুঞ্জন' },
  { char: 'ঝ্র', name: 'ঝ + র', keys: 'Shift+U + Z', example: 'ঝর্না' },
  { char: 'ট্ট', name: 'ট + ট', keys: 'T + G + T', example: 'চট্টগ্রাম, চটি' },
  { char: 'ট্ম', name: 'ট + ম', keys: 'T + G + M', example: 'কুট্মল' },
  { char: 'ট্ব', name: 'ট + ব', keys: 'T + G + H', example: 'খট্বা' },
  { char: 'ট্র', name: 'ট + র', keys: 'T + Z', example: 'ট্রেন, ট্রাক' },
  { char: 'ড্ড', name: 'ড + ড', keys: 'E + G + E', example: 'আড্ডা' },
  { char: 'ড্র', name: 'ড + র', keys: 'E + Z', example: 'ড্রাম, ড্রাইভার' },
  { char: 'ঢ্র', name: 'ঢ + র', keys: 'Shift+E + Z', example: 'মেঢ্র' },
  { char: 'ণ্ট', name: 'ণ + ট', keys: 'Shift+B + G + T', example: 'ঘণ্টা, বণ্টন' },
  { char: 'ণ্ঠ', name: 'ণ + ঠ', keys: 'Shift+B + G + Shift+T', example: 'কণ্ঠ, উৎকণ্ঠা' },
  { char: 'ণ্ড', name: 'ণ + ড', keys: 'Shift+B + G + E', example: 'দণ্ড, পাণ্ডব' },
  { char: 'ণ্ঢ', name: 'ণ + ঢ', keys: 'Shift+B + G + Shift+E', example: 'আষাঢ়' },
  { char: 'ণ্ণ', name: 'ণ + ণ', keys: 'Shift+B + G + Shift+B', example: 'বিষণ্ণ, লাবণ্য' },
  { char: 'ণ্য', name: 'ণ + য', keys: 'Shift+B + Shift+Z', example: 'পুণ্য, অরণ্য' },
  { char: 'ত্ত', name: 'ত + ত', keys: 'K + G + K', example: 'উত্তর, বৃত্ত' },
  { char: 'ত্ত্ব', name: 'ত + ত + ব', keys: 'K + G + K + G + H', example: 'তত্ত্ব, গুরুত্ব' },
  { char: 'ত্থ', name: 'ত + থ', keys: 'K + G + Shift+K', example: 'উত্থান' },
  { char: 'ত্ন', name: 'ত + ন', keys: 'K + G + B', example: 'রত্ন, যত্ন' },
  { char: 'ত্ম', name: 'ত + ম', keys: 'K + G + M', example: 'আত্মা, মহাত্মা' },
  { char: 'ত্ব', name: 'ত + ব', keys: 'K + G + H', example: 'গুরুত্ব, ঘনত্ব' },
  { char: 'ত্র', name: 'ত + র', keys: 'K + Z', example: 'ছাত্র, রাত্রি' },
  { char: 'ত্র্য', name: 'ত + র + য', keys: 'K + Z + Shift+Z', example: 'ত্র্যহস্পর্শ' },
  { char: 'থ্ব', name: 'থ + ব', keys: 'Shift+K + G + H', example: 'পৃথ্বী' },
  { char: 'থ্য', name: 'থ + য', keys: 'Shift+K + Shift+Z', example: 'তথ্য, পথ্য' },
  { char: 'থ্র', name: 'থ + র', keys: 'Shift+K + Z', example: 'নৃথ্র' },
  { char: 'দ্দ', name: 'দ + দ', keys: 'L + G + L', example: 'উদ্দেশ্য, রদ্দ' },
  { char: 'দ্ধ', name: 'দ + ধ', keys: 'L + G + Shift+L', example: 'যুদ্ধ, শুদ্ধ' },
  { char: 'দ্ব', name: 'দ + ব', keys: 'L + G + H', example: 'দ্বার, দ্বিতীয়' },
  { char: 'দ্ভ', name: 'দ + ভ', keys: 'L + G + Shift+H', example: 'অদ্ভুত, উদ্ভব' },
  { char: 'দ্ম', name: 'দ + ম', keys: 'L + G + M', example: 'পদ্ম, ছদ্মবেশ' },
  { char: 'দ্র', name: 'দ + র', keys: 'L + Z', example: 'ভদ্র, চন্দ্র' },
  { char: 'ধ্ব', name: 'ধ + ব', keys: 'Shift+L + G + H', example: 'ধ্বনি, ধ্বংস' },
  { char: 'ধ্য', name: 'ধ + য', keys: 'Shift+L + Shift+Z', example: 'ধ্যান, মধ্য' },
  { char: 'ধ্র', name: 'ধ + র', keys: 'Shift+L + Z', example: 'ধ্রুব' },
  { char: 'ধ্ন', name: 'ধ + ন', keys: 'Shift+L + G + B', example: 'কৃতঘ্ন' },
  { char: 'ন্ট', name: 'ন + ট', keys: 'B + G + T', example: 'সেন্টার, প্যান্ট' },
  { char: 'ন্ঠ', name: 'ন + ঠ', keys: 'B + G + Shift+T', example: 'লন্ঠন' },
  { char: 'ন্ড', name: 'ন + ড', keys: 'B + G + E', example: 'প্যান্ডেল, ফান্ড' },
  { char: 'ন্ত', name: 'ন + ত', keys: 'B + G + K', example: 'শান্ত, অনন্ত' },
  { char: 'ন্ত্র', name: 'ন + ত + র', keys: 'B + G + K + Z', example: 'যন্ত্র, মন্ত্র' },
  { char: 'ন্ত্ব', name: 'ন + ত + ব', keys: 'B + G + K + G + H', example: 'সান্ত্বনা' },
  { char: 'ন্থ', name: 'ন + থ', keys: 'B + G + Shift+K', example: 'গ্রন্থ, পন্থী' },
  { char: 'ন্দ', name: 'ন + দ', keys: 'B + G + L', example: 'আনন্দ, সুন্দর' },
  { char: 'ন্দ্র', name: 'ন + দ + র', keys: 'B + G + L + Z', example: 'চন্দ্র, ইন্দ্র' },
  { char: 'ন্ধ', name: 'ন + ধ', keys: 'B + G + Shift+L', example: 'অন্ধ, বন্ধু' },
  { char: 'ন্ন', name: 'ন + ন', keys: 'B + G + B', example: 'অন্ন, কান্না' },
  { char: 'ন্ম', name: 'ন + ম', keys: 'B + G + M', example: 'জন্ম, উন্মাদ' },
  { char: 'ন্ব', name: 'ন + ব', keys: 'B + G + H', example: 'অন্বেষণ, তন্বী' },
  { char: 'প্ট', name: 'প + ট', keys: 'R + G + T', example: 'ক্যাপ্টেন' },
  { char: 'প্ত', name: 'প + ত', keys: 'R + G + K', example: 'সপ্ত, সুপ্ত' },
  { char: 'প্ন', name: 'প + ন', keys: 'R + G + B', example: 'স্বপ্ন' },
  { char: 'প্প', name: 'প + প', keys: 'R + G + R', example: 'থাপ্পড়, বাপ্পা' },
  { char: 'প্য', name: 'প + য', keys: 'R + Shift+Z', example: 'প্রাপ্য' },
  { char: 'প্র', name: 'প + র', keys: 'R + Z', example: 'প্রথম, প্রণাম' },
  { char: 'প্ল', name: 'প + ল', keys: 'R + G + Shift+V', example: 'প্লাবন, প্ল্যান' },
  { char: 'প্স', name: 'প + স', keys: 'R + G + N', example: 'লিপ্সা' },
  { char: 'ফ্র', name: 'ফ + র', keys: 'Shift+R + Z', example: 'ফ্রেম, ফ্রান্স' },
  { char: 'ফ্ল', name: 'ফ + ল', keys: 'Shift+R + G + Shift+V', example: 'ফ্ল্যাট, ফ্লুট' },
  { char: 'ব্জ', name: 'ব + জ', keys: 'H + G + U', example: 'সব্জি' },
  { char: 'ব্দ', name: 'ব + দ', keys: 'H + G + L', example: 'শব্দ, শতাব্দী' },
  { char: 'ব্ধ', name: 'ব + ধ', keys: 'H + G + Shift+L', example: 'স্তব্ধ, লব্ধ' },
  { char: 'ব্ব', name: 'ব + ব', keys: 'H + G + H', example: 'আব্বা, ডিব্বা' },
  { char: 'ব্ল', name: 'ব + ল', keys: 'H + G + Shift+V', example: 'ব্লক, ব্ল্যাক' },
  { char: 'ব্র', name: 'ব + র', keys: 'H + Z', example: 'তীব্র, ব্রত' },
  { char: 'ভ্য', name: 'ভ + য', keys: 'Shift+H + Shift+Z', example: 'সভ্য, অভ্যাস' },
  { char: 'ভ্র', name: 'ভ + র', keys: 'Shift+H + Z', example: 'ভ্রমণ, ভ্রাতা' },
  { char: 'ম্প', name: 'ম + প', keys: 'M + G + R', example: 'সম্পদ, চম্পা' },
  { char: 'ম্প্র', name: 'ম + প + র', keys: 'M + G + R + Z', example: 'সম্প্রদায়' },
  { char: 'ম্ফ', name: 'ম + ফ', keys: 'M + G + Shift+R', example: 'লম্ফ, গুস্ফ' },
  { char: 'ম্ব', name: 'ম + ব', keys: 'M + G + H', example: 'অম্বল, কম্বল' },
  { char: 'ম্ভ', name: 'ম + ভ', keys: 'M + G + Shift+H', example: 'সম্ভব, আরম্ভ' },
  { char: 'ম্ম', name: 'ম + ম', keys: 'M + G + M', example: 'সম্মান, সম্মতি' },
  { char: 'ম্ল', name: 'ম + ল', keys: 'M + G + Shift+V', example: 'ম্লান' },
  { char: 'র্ক', name: 'র + ক (রেফ)', keys: 'Shift+A + J', example: 'তর্ক, মর্কট' },
  { char: 'র্গ', name: 'র + গ (রেফ)', keys: 'Shift+A + O', example: 'বর্গ, সর্গ' },
  { char: 'র্ষ', name: 'র + ষ (রেফ)', keys: 'Shift+A + Shift+N', example: 'বর্ষা, হর্ষ' },
  { char: 'র্শ', name: 'র + শ (রেফ)', keys: 'Shift+A + Shift+M', example: 'আদর্শ, দর্শন' },
  { char: 'ল্ক', name: 'ল + ক', keys: 'Shift+V + G + J', example: 'বল্কল' },
  { char: 'ল্গ', name: 'ল + গ', keys: 'Shift+V + G + O', example: 'বল্গা' },
  { char: 'ল্ট', name: 'ল + ট', keys: 'Shift+V + G + T', example: 'উল্টো, পল্টন' },
  { char: 'ল্প', name: 'ল + প', keys: 'Shift+V + G + R', example: 'গল্প, অল্প' },
  { char: 'ল্ল', name: 'ল + ল', keys: 'Shift+V + G + Shift+V', example: 'আল্লাহ, মল্ল' },
  { char: 'শ্চ', name: 'শ + চ', keys: 'Shift+M + G + Y', example: 'নিশ্চয়, আশ্চর্য' },
  { char: 'শ্ন', name: 'শ + ন', keys: 'Shift+M + G + B', example: 'প্রশ্ন' },
  { char: 'শ্ম', name: 'শ + ম', keys: 'Shift+M + G + M', example: 'শ্মশান, কাশ্মীর' },
  { char: 'শ্র', name: 'শ + র', keys: 'Shift+M + Z', example: 'শ্রাবণ, শ্রদ্ধা' },
  { char: 'শ্ল', name: 'শ + ল', keys: 'Shift+M + G + Shift+V', example: 'শ্লেষ, শ্লোক' },
  { char: 'ষ্ট', name: 'ষ + ট', keys: 'Shift+N + G + T', example: 'কষ্ট, নষ্ট' },
  { char: 'ষ্ঠ', name: 'ষ + ঠ', keys: 'Shift+N + G + Shift+T', example: 'শ্রেষ্ঠ, জ্যেষ্ঠ' },
  { char: 'ষ্ণ', name: 'ষ + ণ', keys: 'Shift+N + G + Shift+B', example: 'কৃষ্ণ, তৃষ্ণা' },
  { char: 'ষ্প', name: 'ষ + প', keys: 'Shift+N + G + R', example: 'পুষ্প, নিষ্পাপ' },
  { char: 'ষ্ফ', name: 'ষ + ফ', keys: 'Shift+N + G + Shift+R', example: 'নিষ্ফল' },
  { char: 'স্ক', name: 'স + ক', keys: 'N + G + J', example: 'স্কুল, ভাস্কর' },
  { char: 'স্খ', name: 'স + খ', keys: 'N + G + Shift+J', example: 'স্খলন' },
  { char: 'স্ট', name: 'স + ট', keys: 'N + G + T', example: 'স্টেশন, মাস্টার' },
  { char: 'স্ট্র', name: 'স + ট + র', keys: 'N + G + T + Z', example: 'রাষ্ট্র, অস্ট্রিয়া' },
  { char: 'স্ত', name: 'স + ত', keys: 'N + G + K', example: 'ব্যস্ত, সমস্ত' },
  { char: 'স্ত্র', name: 'স + ত + র', keys: 'N + G + K + Z', example: 'স্ত্রী, অস্ত্র' },
  { char: 'স্থ', name: 'স + থ', keys: 'N + G + Shift+K', example: 'স্থান, স্বাস্থ্য' },
  { char: 'স্ন', name: 'স + ন', keys: 'N + G + B', example: 'স্নান, স্নেহ' },
  { char: 'স্প', name: 'স + প', keys: 'N + G + R', example: 'স্পর্শ, স্পষ্ট' },
  { char: 'স্ফ', name: 'স + ফ', keys: 'N + G + Shift+R', example: 'স্ফীত, স্ফুলিঙ্গ' },
  { char: 'স্ব', name: 'স + ব', keys: 'N + G + H', example: 'স্বাধীন, স্বপ্ন' },
  { char: 'স্ম', name: 'স + ম', keys: 'N + G + M', example: 'স্মরণ, বিস্ময়' },
  { char: 'স্ল', name: 'স + ল', keys: 'N + G + Shift+V', example: 'স্লোগান, স্লিপ' },
  { char: 'হ্ণ', name: 'হ + ণ', keys: 'I + G + Shift+B', example: 'অপরাহ্ণ, মধ্যাহ্ণ' },
  { char: 'হ্ন', name: 'হ + ন', keys: 'I + G + B', example: 'চিহ্ন, বহ্নি' },
  { char: 'হ্ম', name: 'হ + ম', keys: 'I + G + M', example: 'ব্রাহ্মণ, ব্রহ্ম' },
  { char: 'হৃ', name: 'হ + ঋ', keys: 'I + A', example: 'হৃদয়, হৃৎপিণ্ড' },
  { char: 'হ্ল', name: 'হ + ল', keys: 'I + G + Shift+V', example: 'আহ্লাদ' },
  { char: 'হ্ব', name: 'হ + ব', keys: 'I + G + H', example: 'আহ্বান, বিহ্বল' },
  { char: 'হ্র', name: 'হ + র', keys: 'I + Z', example: 'হ্রাস, হ্রদ' },
];
